services:
  evrinoma.dto.factory:
    class: Evrinoma\DtoBundle\Factory\FactoryDto
    arguments:
      - '@event_dispatcher'
      - '@evrinoma.dto.service.registry'

  Evrinoma\DtoBundle\Factory\FactoryDto:
    alias: evrinoma.dto.factory
    public: true

  evrinoma.dto.listener.subscriber:
    class: Evrinoma\DtoBundle\Subscriber\DtoAnnotationSubscriber
    arguments:
      - '@annotations.reader'
      - '@evrinoma.dto.factory'
    tags:
      - { name: kernel.event_subscriber }

  Evrinoma\DtoBundle\Subscriber\DtoAnnotationSubscriber:
    alias: evrinoma.dto.listener.subscriber
    public: true

  evrinoma.dto.service.registry:
    class: Evrinoma\DtoBundle\Registry\ServiceRegistry
    public: true
    arguments:
      - '%kernel.cache_dir%'
      - '@annotations.reader'

  Evrinoma\DtoBundle\Registry\ServiceRegistryInterface:
    alias: evrinoma.dto.service.registry

  evrinoma.dto.service.identity.class:
    class: Evrinoma\DtoBundle\Service\Identity\ClassIdentity
    autowire: true

  Evrinoma\DtoBundle\Service\Identity\ClassIdentity:
    alias: evrinoma.dto.service.identity.class
    public: true

  evrinoma.dto.service.identity.md5:
    class: Evrinoma\DtoBundle\Service\Identity\Md5Identity
    autowire: true

  Evrinoma\DtoBundle\Service\Identity\Md5Identity:
    alias: evrinoma.dto.service.identity.md5
    public: true
