services:
  evrinoma.dto.factory:
    class: Evrinoma\DtoBundle\Factory\FactoryDto
    arguments:
      - '@event_dispatcher'

  Evrinoma\DtoBundle\Factory\FactoryDto:
    alias: evrinoma.dto.factory
    public: true

  evrinoma.dto.listener.subscriber:
    class: Evrinoma\DtoBundle\Subscriber\DtoAnnotationSubscriber
    arguments:
      - '@annotations.reader'
      - '@evrinoma.dto.factory'
    tags:
      - { name: kernel.event_subscriber }

  Evrinoma\DtoBundle\Subscriber\DtoAnnotationSubscriber:
    alias: evrinoma.dto.listener.subscriber
    public: true
